# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e043286333396965cd5a3eee78108b16dac5bea4ebc83cba026df91eb2592a936c7a146ec5b4fefac7f7c0939d8b0733826cafada368457599b2f9bcce7bbc2d

test:
  secret_key_base: 3e92c2caa655a2962e7d274d3fbcadbe2e91124c493a98f1a3636bf9e7448c6d51491b72f5b080395d9ec19cb18376c8109ae29fcb51233e6415bfb68366dbb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
